export enum ACTIONS_TYPE {
    SET_USER_DATA = 'SET_USER_DATA',
    INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS',

    ADD_MESSAGE = 'ADD_MESSAGE',

    ADD_POST = 'ADD_POST',
    SET_USER_PROFILE = 'SET_USER_PROFILE',
    SET_USER_STATUS = 'SET_USER_STATUS',
    UPDATE_USER_STATUS = 'UPDATE_USER_STATUS',

    FOLLOW = 'FOLLOW',
    UNFOLLOW = 'UNFOLLOW',
    SET_USERS = 'SET_USERS',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT',
    TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING',
    TOGGLE_IS_FOLLOWING_PROGRESS = 'TOGGLE_IS_FOLLOWING_PROGRESS',
}